version: '3.3'
services: 
    node:
        build: 
            context: ./
            dockerfile: Dockerfile
        volumes: 
            - type: bind
              source: ./
              target: /App
        ports:
            - 3000:3000
